---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-production
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/lneves75/argocd-apps.git
        revision: master
        files:
          - path: "apps/production/"
  template:
    metadata:
      name: '{{ name }}-{{ environment }}'
      labels:
        version: '{{ tag }}'
    spec:
      project: '{{ project }}'
      source:
        repoURL: https://github.com/lneves75/helm-chart.git
        targetRevision: '{{ chart.version }}'
        path: '.'
        helm:
          parameters:
            - name: image.tag
              value: '{{ tag }}'
          valueFiles:
            - '{{ valueFiles }}'
      destination:
        name: '{{ cluster }}'
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=false
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
