---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: business
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/lneves75/argocd-apps.git
        revision: HEAD
        files:
        - path: apps/**/*
  template:
    metadata:
      name: '{{ .name }}-{{ .path.path }}'
      labels:
        version: '{{ .tag }}'
    spec:
      project: '{{ .project }}'
      source:
        repoURL: https://github.com/lneves75/helm-chart.git
        targetRevision: '{{ .chart.version }}'
        path: '.'
        helm:
          releaseName: '{{ .name }}'
          parameters:
            - name: image.tag
              value: '{{ .tag }}'
          valueFiles:
            - '{{ .valueFiles }}'
      destination:
        name: '{{ .cluster }}'
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=false
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
