apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webapp
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    #  - pullRequest:
    #      github:
    #        # The GitHub organization or user.
    #        owner: lneves75
    #        # The Github repository
    #        repo: webapp
    #        # Labels is used to filter the PRs that you want to target. (optional)
    #        labels:
    #        - preview
    #      requeueAfterSeconds: 1800
  - git:
      repoURL: https://github.com/lneves75/argocd-apps.git
      revision: master
      files:
        - path: "apps/"
  template:
    metadata:
      name: webapp
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/lneves75/helm-chart.git
        path: "."
        targetRevision: HEAD
        helm:
          parameters:
          - name: image.tag
            value: 9e80cccb0aecc050fa9ed766c0e50266e8e4dc77
          valueFiles:
            - https://raw.githubusercontent.com/lneves75/webapp/refs/heads/master/helm/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=false
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

