apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webapp-preview
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: lneves75
        # The Github repository
        repo: webapp
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
        - built
        - preview
      requeueAfterSeconds: 1800
  template:
    metadata:
      name: webapp-{{.number}}
      namespace: argocd
      labels:
        version: '{{ .head_sha }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/lneves75/helm-chart.git
        path: "."
        targetRevision: master
        helm:
          parameters:
            - name: image.tag
              value: '{{ .head_sha }}'
          valueFiles:
          - https://raw.githubusercontent.com/lneves75/webapp/{{ .head_sha }}/helm/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: preview
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=false
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

